version: '3.8'
services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - ./src/database/init/setup.sql:/docker-entrypoint-initdb.d/setup.sql
